# Generated by Django 5.2.9 on 2025-12-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlexItAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='workout',
            new_name='workouts',
        ),
        migrations.RenameField(
            model_name='workoutexercise',
            old_name='routine',
            new_name='workout',
        ),
    ]
