# Generated by Django 5.2.9 on 2025-12-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlexItAPI', '0003_rename_exercise_workoutsession_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='exercises', through='FlexItAPI.ExerciseLog', to='FlexItAPI.exercise'),
        ),
    ]
