# Generated by Django 5.2.9 on 2025-12-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlexItAPI', '0005_exercise_distance_exercise_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('ext', 'extreme'), ('hig', 'high'), ('med', 'medium'), ('low', 'low')], default='med', max_length=3),
        ),
        migrations.AddField(
            model_name='workout',
            name='difficulty',
            field=models.CharField(choices=[('ext', 'extreme'), ('hig', 'high'), ('med', 'medium'), ('low', 'low')], default='med', max_length=3),
        ),
    ]
