# Generated by Django 5.2.9 on 2025-12-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlexItAPI', '0002_rename_workout_exercise_workouts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutsession',
            old_name='exercise',
            new_name='exercises',
        ),
    ]
