# Generated by Django 5.2.9 on 2025-12-23 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlexItAPI', '0004_alter_workoutsession_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='series',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='FlexItAPI.workoutsession'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='logged_sessions', through='FlexItAPI.ExerciseLog', to='FlexItAPI.exercise'),
        ),
    ]
