# Generated by Django 5.2.9 on 2026-01-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlexItAPI', '0006_exercise_difficulty_workout_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='distance',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='duration',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='repetitions',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='series',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='distance',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='duration',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='notes',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='repetitions',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='series',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='weight',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
