# Generated by Django 5.2.9 on 2026-03-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlexItAPI', '0007_alter_exercise_distance_alter_exercise_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='focus_area',
            field=models.CharField(blank=True, choices=[('bac', 'back'), ('cht', 'chest'), ('arm', 'arms'), ('leg', 'legs'), ('shd', 'shoulder'), ('oth', 'other')], max_length=3),
        ),
        migrations.AlterField(
            model_name='workout',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
